# -*- coding: utf-8 -*-
"""BudgetTracker.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/19mTcz-jBNM_gr6Z4G2DyyU0wvXdqHrcA
"""

class BudgetTracker:
    def __init__(self, initial_budget):
        self.budget = initial_budget
        self.expenses = []

    def add_expense(self, amount, category):
        self.expenses.append({'amount': amount, 'category': category})
        self.budget -= amount

    def get_total_expenses(self):
        return sum(expense['amount'] for expense in self.expenses)

    def get_remaining_budget(self):
        return self.budget

    def get_expenses_by_category(self, category):
        return [expense for expense in self.expenses if expense['category'] == category]


def main():
    initial_budget = float(input("Enter your initial budget: "))
    tracker = BudgetTracker(initial_budget)

    while True:
        print("\nOptions:")
        print("1. Add an expense")
        print("2. View total expenses")
        print("3. View remaining budget")
        print("4. View expenses by category")
        print("5. Exit")

        choice = input("Enter your choice: ")

        if choice == '1':
            amount = float(input("Enter the amount of the expense: "))
            category = input("Enter the category of the expense: ")
            tracker.add_expense(amount, category)
            print("Expense added successfully!")

        elif choice == '2':
            total_expenses = tracker.get_total_expenses()
            print(f"Total expenses: ${total_expenses:.2f}")

        elif choice == '3':
            remaining_budget = tracker.get_remaining_budget()
            print(f"Remaining budget: ${remaining_budget:.2f}")

        elif choice == '4':
            category = input("Enter the category to view expenses: ")
            expenses_by_category = tracker.get_expenses_by_category(category)
            if expenses_by_category:
                print(f"Expenses in category '{category}':")
                for expense in expenses_by_category:
                    print(f"${expense['amount']:.2f}")
            else:
                print("No expenses found in this category.")

        elif choice == '5':
            print("Exiting...")
            break

        else:
            print("Invalid choice. Please enter a valid option.")


if __name__ == "__main__":
    main()